[package]
name = "rusty-scout"
version = "1.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
colored = "2.0"
indicatif = "0.17"
ignore = "0.4"
rayon = "1.8"
regex = "1.10"

[dev-dependencies]
tempfile = "3.8"